environment:
  matrix:
    - nodejs_version: "6"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - yarn --version
  - node tests\run_e2e.js --appveyor

build: off

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"
