dist: trusty
sudo: required

language: node_js

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null

matrix:
  fast_finish: true
  allow_failures:
    - env: NODE_SCRIPT="tests/run_e2e.js --nightly"
    - env: NODE_SCRIPT="tests/run_e2e.js --ng2"
    - env: DEPLOY_SCRIPT="scripts/git-builds.js"
    - node_js: "7"
  include:
    - node_js: "6"
      os: linux
      env: SCRIPT=lint
    - node_js: "6"
      os: linux
      env: SCRIPT=build
    - node_js: "6"
      os: linux
      env: SCRIPT=test
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT="tests/run_e2e.js --glob=tests/build/**"
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT="tests/run_e2e.js --ignore=**/tests/build/**"
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT="tests/run_e2e.js --eject --glob=tests/build/**"

    # Deploy builds.
    - node_js: "6"
      os: linux
      env:
        - DEPLOY_SCRIPT="scripts/git-builds.js"
        # GITHUB_ACCESS_TOKEN=<github token, a personal access token of the angular-builds account, account access in valentine>
        # This is needed for the e2e Travis matrix task to publish packages to github for continuous packages delivery.
        - secure: "XUM1RCN/ZH34ju2PI9eHPRMnSlbj45XcBx/ZnZ13wfau60iJCveU7Ded8SC8uwGDp58rGGePXyJfh5l5dAnIWbSAGNKlrEgGTr41RSCbyzrV6m4lAcwNzUo/PkKum1vAApk21PqscrSSWOBAOC3nMCln25GLzgUMm6G8FBOc599NuszcoQvru+H+4JthSHn4l/nmeTZDs2oCBvwnmng/78rEW5CXvJEpAwuaaZLvzzIFdoZu+SuceYvGnL5xHo0ppPF/0NYzZlb7KBKREp44Lq1lOKlDtH5wqjEi7b2aA7/GnesOgLUBmbbSVUzmCxs6PtzGhD56aiL2Qtu8c4LZyvNfzPXSLbx8ljYmdytHkio9w3377wWFRXJDfIsgv9JKHxxyA0T34yzQkqWbgWKPMgJ3om+lb875iXAtXfNyS0trnN+rwLZZtFxygjHyx8IWY+NZD5i5fyjMdFyetNxbHe3ktI73nY+Tl6hDqJXvN8WwQlMovLNUMcY4wGUoPooLka9L+94uetbf3U4KVgshrLHI59jMZsO0qrDGsCZMubHEy80acrNkCTi/uGIbVR0KF94z81VF+S7edYv80AkQTRijpgNV34045L/IqSHgbueozRgVFj2arkAGGFjLlZJifmsRC/Eq1ZWkKsKY/1NusKssCRtycJQjeLOW0qV1T0w="

    # Optional builds.
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT="tests/run_e2e.js --ng2"
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT="tests/run_e2e.js --nightly"
    - node_js: "7"
      os: linux
      env: NODE_SCRIPT=tests/run_e2e.js

before_install:
  # Use a virtual display.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  # Install latest chrome.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=/usr/bin/google-chrome; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libappindicator1 fonts-liberation; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i google-chrome*.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "--no-sandbox" > ~/.config/chrome-flags.conf; fi
  # Install yarn.
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set spin false
  - yarn config set progress false

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
  - if [[ "$NODE_SCRIPT" ]]; then node $NODE_SCRIPT; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$DEPLOY_SCRIPT" != "" ]]; then node $DEPLOY_SCRIPT; fi
